openapi: 3.0.1
info:
  title: Detect Text API
  description: API to perform Detect Text
  version: 1.0.0
servers:
  - url: https://ckwl5eo409.execute-api.us-east-1.amazonaws.com
tags:
  - name: Detect Text
    description: Operations related to Detect Text

paths:
  /hackathonDevStage/detectText:
    post:
      tags:
        - Detect Text
      summary: Perform Detect Text
      description: Endpoint to perform Detect text
      operationId: detectText
      requestBody:
        description: Detext text API to read PDF files
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  description: Unique identifier for the user.
                bucketName:
                  type: string
                  description: First name of the user.
                fileName:
                  type: string
                  description: Last name of the user.
      responses:
        '200':
          $ref: "#/components/responses/200DetectText"

components:
  responses:
    200DetectText:
      description: Detect Text Response
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: string
                description: Status Code

              body:
                type: string
                description: Document Body

