openapi: 3.0.1
info:
  title: S3 Object Upload API
  description: API to upload an S3 object
  version: 1.0.0
paths:
  /s3/upload:
    post:
      summary: Upload an S3 object
      description: Upload a document to an S3 bucket
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DetectTextRequest'
      responses:
        '200':
          description: Successfully uploaded the S3 object
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: S3 object uploaded successfully
                  s3Object:
                    $ref: '#/components/schemas/S3Object'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid input data
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal server error
components:
  schemas:
    s3Object:
      type: object
      properties:
        bucket:
          type: string
          example: hackathonbsp
        userId:
          type: string
          example: "12345"
        name:
          type: string
          example: "DTI Business Name Certification - Liza Garcia.pdf"
      required:
        - Bucket
        - userId
        - Name

    DetectTextRequest:
      type: object
      properties:
        s3Object:
          $ref: '#/components/schemas/S3Object'
      required:
        - s3Object